rstudio/shinyloadtest

R/shiny-recorder.R
This stops the error "invalid connection".
File connections should be closed properly otherwise a warning appears at a later time.
It makes sense to close the file in the `stop` method.  However once it finishes, other close events are fired after the 'tick'.  This prevents other writeEvent calls from being fired as the writing to file has been closed.
By using `cat(..., append = TRUE)` we do not need to carry a file connection and it will always append to the existing log file until the next recorder initialization where `append = FALSE`.
=> writeEvent uses `cat(..., append = TRUE)` not a file connection

R/shiny-recorder.R, man/record_session.Rd
This is mostly for security -- since we collect credentials from people, we should be available only on localhost by default.
It also fixes a problem on Windows, which is that 0.0.0.0 isn't an actual host you can navigate to, so `record_session` with `open_browser = TRUE` (the default) opens a browser but the browser can't find the host.
=> Bind to 127.0.0.1 by default instead of to 0.0.0.0

R/shiny-recorder.R
This fixes two problems with recording output:
* The lack of a `:` between minutes and seconds in the timestamp makes the timestamp an invalid ISO date/time stamp, and so extra parsing hoops are required in `shinycannon` without this fix.
* The `datafile` field of `REQ_POST` records contained the full path to the datafile, which we don't want, because we want the path of data files to be relative to the recording. So instead of `datafile: "/tmp/foo.log.post.0"` we want `datafile: "foo.log.post.0"`
Once this is merged I will modify the recordings that @shalutiwari attached to https://trello.com/c/Q5kRB9u9 before she left so that she won't have to re-do them.
=> Fix timestamp format and datafile name

R/shiny-recorder.R
This was a code review thing I forgot; the regex that parses out the sockjs ROBUST_ID will continue to work if `n=...` should appear later in the URL string.
=> Still work when ROBUST_ID appears anywhere in a __sockjs__/ URL

R/shiny-recorder.R
Example effect:
```
> shinyloadtest::record_session("https://gallery.shinyapps.io/012-datatables/", output_file = "/tmp/dt.log")
Error in .subset2(public_bind_env, "initialize")(...) : 
Recording shinyapps.io apps is not supported 
```
=> Exit early if attempt made to record shinyapps.io app

R/shiny-recorder.R
We don't ignore the `o` WS_RECV or its responses, because doing so required shinycannon to be smarter than we want it to be.
=> Record o message again

R/make_report.R
It is really rare if it doesn't and is prolly the user's doing
=> make tempdir not check if it exists

Makefile
This small change makes `make clean` work even if `vignettes/test_sessions/*` directories don't exist yet. I also moved the step that deletes `RELEASE_URLS.txt` into the `RELEASE_URLS.txt` target, since updating that is a separate task than cleaning up.
=> Clean if directories don't exist

R/analysis.R
If no maintenance period can be found, then use all sessions as maintenance.  
A message is not printed if there is only one session per simulated user. (It is impossible to have a true maintenance period in this situation.)
=> Present message when recording does not have a 'true' maintenance period

docs/articles/limitations-of-shinyloadtest.html, inst/doc/limitations-of-shinyloadtest.html, vignettes/limitations-of-shinyloadtest.Rmd
@slopp spent time trying to get this to work because we forgot to document that it doesn't (yet). Added to limitations doc.
=> Add Rmd + runtime shiny to limitations list

index.Rmd
This PR closes #51 by adding a few sentences about installing `OpenSSL` and development libraries for Debian/Ubuntu and Redhat/Fedora/CentOS systems.  Happy to modify the wording if anything is not clear.
=> Add OpenSSL installation notes for Linux (#51)

vignettes/limitations-of-shinyloadtest.Rmd
This adds a bullet to the Limitations vignette, documenting the fact that recordings are server-dependent.
=> Add record/playback limitation

R/plotting.R
Drops an empty "Cutoff" legend box from latency plot as it can not be displayed.
Now looks like:
=> Clean up legend

R/auth.R
I missed a place where the new enum-based server type needed to be used which broke recording of SSP apps requiring authentication.
While I was in there I made sure `getInputs()` always a returns a (possibly empty) data frame.
Then, I check both for 200 and for 302 to check for auth success (SSP redirects after authenticating)
=> Fix authenticated SSP recording bug introduced by #107

DESCRIPTION, R/analysis.R, R/make_report.R, R/shiny-recorder.R, man/load_runs.Rd, man/record_session.Rd, man/shinyloadtest_report.Rd
@shalutiwari discovered recently that we don't document anywhere how POST requests are handled, and the fact that files other than the recording are created when HTTP POSTs are sent through the reverse proxy.
I expanded the `record_session()` documentation to include a section describing how we handle POSTs. Along the way, I took the opportunity to get us rolling on [Markdown-flavored Roxygen](https://cran.r-project.org/web/packages/roxygen2/vignettes/markdown.html).
Note that this will need the `make site` treatment once accepted.
=> Use Markdown in Roxygen comments, expand record_session docs

R/shiny-recorder.R
It can be confusing to people that when data is POSTed, such as via DT or fileInput, the uploaded data is not contained in the recording file but instead is stored in auxiliary files.
Recently we [documented](https://github.com/rstudio/shinyloadtest/pull/113) the behavior, which will help.
This PR goes a step further and notifies the user when the recording stops that files have been created.
Here's an example of what the new behavior looks like in the R console:
```
> record_session("https://my.rsc.com/content/4223/", output_file = "upload.log")
Listening on 127.0.0.1:8600
Navigating to: http://127.0.0.1:8600/
Client connected
Client disconnected
Stopping server
Note: uploaded files to keep with recording file:
upload.log.post.0
upload.log.post.1
Server disconnected
```
=> Display a message with created files when recording stops

NEWS.md, R/detect.R, tests/testthat/01_hello.html, tests/testthat/r_project.html, tests/testthat/test-app-detection.R
*Corresponds to rstudio/shinycannon#42, please see that PR for details.*
=> Simplify app detection, complements rstudio/shinycannon#42

R/shiny-recorder.R
Previously, if we obtained any cookies from the authentication request we sent, we were adding a second `Cookie` header to the client's request instead of overwriting their provided `cookie` header.
This meant that if the client already had a meaningful cookie left over from some previous recording session (such as the `session_state` cookie) it would be sent. If the server being recorded wasn't the same as that which generated the cookie, it would fail to decrypt the cookie and the client would be sent to the login screen.
This fixes the casing of the header field we overwrite so that only one `cookies` header is sent, which assures that only one (and the correct) session_state cookie is sent.
=> Properly overwrite request cookies if authentication is used

R/auth.R, R/shiny-recorder.R, R/url.R, tests/testthat/test-url-construction.R
There are 3 changes in this PR. One is big and two are small.
1. Big: URLBuilder improvements. Details below.
1. Small: Simplify `Host` header creation. Previously we included the port in the `Host` header after the domain, if the target application had an `https` protocol. Apparently, while the port number here is [optional](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Host), no browsers actually do this, and it can confuse proxies. Now, we just use the target domain for `Host` and it seems to have resolved a problem for a customer.
1. Small: Specify proper `content-length` header in response. The `curl` package we use automatically decompresses responses, but we were blindly copying the original response's `content-length` header -- which reflected the gzip'd size -- …
=> Simplify and fix the way URL path components are handled

.travis.yml, DESCRIPTION, R/make_report.R, R/plotting.R, cran-comments.md, man/shinyloadtest_report.Rd, man/slt_plot.Rd, scripts/rhub.R, tests/testthat/test-report-gen.R
This moves exercising `shinyloadtest_report()` from an `@examples` block over to a unit test.
=> Move report gen test from @examples to testthat

R/analysis.R
The current use of `as.tibble` prints a warning when we call `shinyloadtest::load_runs`: 
```
Warning message:
`as.tibble()` is deprecated as of tibble 2.0.0.
Please use `as_tibble()` instead.
The signature and semantics have changed, see `?as_tibble`.
This warning is displayed once every 8 hours.
Call `lifecycle::last_warnings()` to see where this warning was generated. 
```
This PR changes to as_tibble so that we don't have this message anymore.
=> as.tibble => as_tibble

R/plotting.R
Fixes #168: "Returning more (or less) than 1 row per summarise() group was deprecated in dplyr 1.1.0."
I tried `shinyloadtest_report` on a very simple run and the deprecation warning went away, while creating exactly the same HTML file as before the change.
=> Use reframe instead of summarise

DESCRIPTION, NEWS.md, R/make_report.R, R/plotting.R, tests/testthat/test-report-gen.R
Fixes both #163 and #165.
It looks like we go digging around in ggplot2's gtable, looking for the legend, so we can make an SVG out of it. Sometime between ggplot2 3.4.4 and 3.5.1, the layout of that table changed; previously there was a `guide-box` entry, and now there are `guide-box-[top|left|right|bottom]`, only one of which (`bottom`) appears to be non-empty in this code path.
I've added a new `find_legend_grob` function that handles both scenarios.
=> More flexible grob navigation, works with newer ggplot2 versions
